package com.agileboot.admin.customize.service.permission.sync;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.agileboot.domain.system.menu.db.SysMenuEntity;
import com.agileboot.domain.system.menu.db.SysMenuService;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.Test;

class PermissionSyncServiceTest {

    private final PermissionEndpointScanner scanner = mock(PermissionEndpointScanner.class);
    private final SysMenuService menuService = mock(SysMenuService.class);
    private final PermissionSyncService permissionSyncService = new PermissionSyncService(scanner, menuService);

    @Test
    void testPreviewShouldClassifyCreateUpdateConflictUnresolvedAndStaleItems() {
        when(scanner.scan()).thenReturn(new PermissionEndpointScanner.ScanSnapshot(
            6,
            List.of(
                scannedEndpoint("system:user:list", "用户列表", Set.of("GET"), Set.of("/system/users"),
                    Set.of("UserController#list")),
                scannedEndpoint("system:user:add", "新增用户", Set.of("POST"), Set.of("/system/users"),
                    Set.of("UserController#add")),
                scannedEndpoint("system:user:edit", "修改用户", Set.of("PUT"), Set.of("/system/users/{userId}"),
                    Set.of("UserController#edit")),
                scannedEndpoint("system:dept:remove", "删除部门", Set.of("DELETE"), Set.of("/system/dept/{deptId}"),
                    Set.of("DeptController#remove")),
                scannedEndpoint("system:post:query", "岗位详情", Set.of("GET"), Set.of("/system/post/{postId}"),
                    Set.of("PostController#getInfo"))
            ),
            List.of(PermissionSyncItemDTO.builder().permission("system:demo:unsupported").menuName("演示接口")
                .details("不支持的表达式").build()),
            List.of(PermissionSyncItemDTO.builder().menuName("未加权限的接口").details("缺少权限注解").build())
        ));
        when(menuService.list()).thenReturn(List.of(
            pageMenu(5L, 1L, "用户管理", "system:user:list"),
            pageMenu(8L, 1L, "部门管理", "system:dept:list"),
            autoGeneratedButton(22L, 5L, "用户编辑旧名", "system:user:edit"),
            autoGeneratedButton(30L, 5L, "历史权限", "system:user:legacy"),
            nonButtonMenu(39L, 8L, "部门删除菜单", "system:dept:remove")
        ));

        PermissionSyncResultDTO result = permissionSyncService.preview();

        assertTrue(result.isDryRun());
        assertFalse(result.isApplied());
        assertTrue(result.isHasBlockingIssues());
        assertEquals(5, result.getProtectedPermissionCount());
        assertEquals(6, result.getScannedEndpointCount());
        assertEquals(1, result.getCreated().size());
        assertEquals("system:user:add", result.getCreated().get(0).getPermission());
        assertEquals(1, result.getUpdated().size());
        assertEquals("system:user:edit", result.getUpdated().get(0).getPermission());
        assertEquals(1, result.getSkipped().size());
        assertEquals("system:user:list", result.getSkipped().get(0).getPermission());
        assertEquals(1, result.getUnresolved().size());
        assertEquals("system:post:query", result.getUnresolved().get(0).getPermission());
        assertEquals(2, result.getConflicts().size());
        assertEquals(1, result.getUnprotected().size());
        assertEquals(1, result.getStale().size());
        assertEquals("system:user:legacy", result.getStale().get(0).getPermission());
    }

    @Test
    void testSyncShouldApplyCreatesWhenNoBlockingIssues() {
        when(scanner.scan()).thenReturn(new PermissionEndpointScanner.ScanSnapshot(
            2,
            List.of(
                scannedEndpoint("system:user:list", "用户列表", Set.of("GET"), Set.of("/system/users"),
                    Set.of("UserController#list")),
                scannedEndpoint("system:user:add", "新增用户", Set.of("POST"), Set.of("/system/users"),
                    Set.of("UserController#add"))
            ),
            List.of(),
            List.of()
        ));
        when(menuService.list()).thenReturn(List.of(pageMenu(5L, 1L, "用户管理", "system:user:list")));

        PermissionSyncResultDTO result = permissionSyncService.sync();

        assertFalse(result.isDryRun());
        assertTrue(result.isApplied());
        assertFalse(result.isHasBlockingIssues());
        assertEquals(1, result.getCreated().size());
        verify(menuService).save(any(SysMenuEntity.class));
        verify(menuService, never()).updateById(any(SysMenuEntity.class));
    }

    private PermissionEndpointScanner.ScannedPermissionEndpoint scannedEndpoint(String permission, String menuName,
        Set<String> methods, Set<String> paths, Set<String> handlers) {
        return PermissionEndpointScanner.ScannedPermissionEndpoint.builder()
            .permission(permission)
            .menuName(menuName)
            .requestMethods(methods)
            .requestPaths(paths)
            .handlers(handlers)
            .summaries(Set.of(menuName))
            .build();
    }

    private SysMenuEntity pageMenu(Long menuId, Long parentId, String menuName, String permission) {
        SysMenuEntity menu = new SysMenuEntity();
        menu.setMenuId(menuId);
        menu.setParentId(parentId);
        menu.setMenuName(menuName);
        menu.setPermission(permission);
        menu.setMenuType(1);
        menu.setIsButton(false);
        menu.setStatus(1);
        menu.setPath("/test");
        menu.setRouterName("Test");
        return menu;
    }

    private SysMenuEntity autoGeneratedButton(Long menuId, Long parentId, String menuName, String permission) {
        SysMenuEntity menu = new SysMenuEntity();
        menu.setMenuId(menuId);
        menu.setParentId(parentId);
        menu.setMenuName(menuName);
        menu.setPermission(permission);
        menu.setMenuType(0);
        menu.setIsButton(true);
        menu.setStatus(1);
        menu.setPath("");
        menu.setRouterName(" ");
        menu.setMetaInfo("{\"title\":\"" + menuName + "\"}");
        menu.setRemark(PermissionSyncService.AUTO_SYNC_REMARK_PREFIX + permission);
        return menu;
    }

    private SysMenuEntity nonButtonMenu(Long menuId, Long parentId, String menuName, String permission) {
        SysMenuEntity menu = pageMenu(menuId, parentId, menuName, permission);
        menu.setIsButton(false);
        return menu;
    }

}
